apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-es
spec:
  version: 9.2.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  config:
    server.publicBaseUrl: "https://kibana.home.thiis.co:5601"
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      certificate:
        secretName: default-home-thiis-tls