apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-home-thiis-certificate
  namespace: default
spec:
  secretName: default-home-thiis-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  commonName: home.thiis.co
  dnsNames:
  - home.thiis.co
  - '*.home.thiis.co'

