apiVersion: v1 
kind: Service
metadata:
  name: fluentd-headless
  namespace: fluent 
  labels:
    app: fluentd 
spec:
  selector:
    app: fluentd 
  ports:
  - port: 24224
    name: fluentd 
  clusterIP: None
